var quotes = [
    { author: "Walt Disney", quote: "The Way Get Started Is To Quit Talking And Begin Doing."},
    { author: "Winston Churchill", quote: "The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty."},
    { author: "Will Rogers", quote: "Don’t Let Yesterday Take Up Too Much Of Today."},
    { author: "Unknown", quote: "You Learn More From Failure Than From Success. Don’t Let It Stop You. Failure Builds Character."},
    { author: "Walt Disney", quote: "It’s Not Whether You Get Knocked Down, It’s Whether You Get Up."},
    { author: "Vince Lombardi", quote: "The Way Get Started Is To Quit Talking And Begin Doing."},
    { author: "Steve Jobs", quote: "If You Are Working On Something That You Really Care About, You Don’t Have To Be Pushed. The Vision Pulls You."},
    { author: "Rob Siltanen", quote: "People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do."},
    { author: "Og Mandino", quote: "Failure Will Never Overtake Me If My Determination To Succeed Is Strong Enough."},
    { author: "Mohnish Pabrai", quote: "Entrepreneurs Are Great At Dealing With Uncertainty And Also Very Good At Minimizing Risk. That’s The Classic Entrepreneur."},
    { author: "Maya Angelou", quote: "We May Encounter Many Defeats But We Must Not Be Defeated."},
    { author: "Johann Wolfgang Von Goethe", quote: "Knowing Is Not Enough; We Must Apply. Wishing Is Not Enough; We Must Do."},
    { author: "Brian Tracy", quote: "Imagine Your Life Is Perfect In Every Respect; What Would It Look Like?"},
    { author: "Dr. Henry Link", quote: "We Generate Fears While We Sit. We Overcome Them By Action."},
    { author: "Henry Ford", quote: "Whether You Think You Can Or Think You Can’t, You’re Right."},
    { author: "Helen Keller", quote: "Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing."},
    { author: "Hasidic Proverb", quote: "The Man Who Has Confidence In Himself Gains The Confidence Of Others."},
    { author: "Franklin D. Roosevelt", quote: "The Only Limit To Our Realization Of Tomorrow Will Be Our Doubts Of Today."},
    { author: "Albert Einstein", quote: "Creativity Is Intelligence Having Fun."},
    { author: "Don Zimmer", quote: "What You Lack In Talent Can Be Made Up With Desire, Hustle And Giving 110% All The Time."},
    { author: "Theodore Roosevelt", quote: "Do What You Can With All You Have, Wherever You Are."},
    { author: "Brian Tracy", quote: "Develop An ‘Attitude Of Gratitude’. Say Thank You To Everyone You Meet For Everything They Do For You."},
    { author: "C.S. Lewis", quote: "You Are Never Too Old To Set Another Goal Or To Dream A New Dream."},
    { author: "Confucius", quote: "To See What Is Right And Not Do It Is A Lack Of Courage."},
    { author: "Brian Tracy", quote: "Reading Is To The Mind, As Exercise Is To The Body."},
    { author: "Brian Tracy", quote: "Fake It Until You Make It! Act As If You Had All The Confidence You Require Until It Becomes Your Reality."},
    { author: "Brian Tracy", quote: "The Future Belongs To The Competent. Get Good, Get Better, Be The Best!"},
    { author: "Jack Canfield", quote: "For Every Reason It’s Not Possible, There Are Hundreds Of People Who Have Faced The Same Circumstances And Succeeded."},
    { author: "John Wooden", quote: "Things Work Out Best For Those Who Make The Best Of How Things Work Out."},
    { author: "Marcus Tullius Cicero", quote: "A Room Without Books Is Like A Body Without A Soul."},
    { author: "Oprah Winfrey", quote: "Be thankful for what you have; you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough."},
    { author: "Ralph Emerson", quote: "Adopt the pace of nature, her secret is patience."},
    { author: "Unknown", quote: "To reach your greatest potential you'll have to fight your greatest fears."},
    { author: "Eleanor Roosevelt", quote: "Learn from the mistakes of others. You can’t live long enough to make them all yourself."},
    { author: "Richard Parkes Cordock", quote: "You must expect failure as part of your journey of success, failure and success go hand in hand, you cannot have one without the other."},
    { author: "Unknown", quote: "Let go of the thoughts that don't make you strong."},
    { author: "Stephen King", quote: "You can, you should, and if you’re brave enough to start, you will."},
    { author: "Jimmy Johnson", quote: "The difference between ordinary and extraordinary is that little extra."},
    { author: "Dr. Seuss", quote: "Why fit in when you were born to stand out?"},
    { author: "Mandy Hale", quote: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong."},
    { author: "William Arthur Ward", quote: "If you can imagine it, you can achieve it. If you can dream it, you can become it."},
    { author: "Grayson Marshall", quote: "If people aren't laughing at your dreams, your dreams aren't big enough."},
    { author: "AWOLNATION, \"Kill Your Heroes\"", quote: "Never let your fear decide your fate."},
    { author: "Seneca", quote: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult."},
    { author: "Chinese Proverb", quote: "The best time to plant a tree was 20 years ago. The second best time is now."},
    { author: "Helen Keller", quote: "Never bend your head. Always hold it high. Look the world straight in the face."},
    { author: "Confucius", quote: "One who knows all the answers has not been asked all the questions."},
    { author: "Diane von Furstenberg", quote: "You are the one that possesses the keys to your being. You carry the passport to your own happiness."},
    { author: "Russell Brand", quote: "Choose your heroes or they will be chosen for you."}
];
